### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'convert': 'convert'

### ISSUE THREAD

**Issue by BumpierZulu9930** [aayars/py-noisemaker#5]
This error seems to happen every time `animaker` is used (for me, at least). It all seems to root from `subprocess.check_call()`, according to this traceback:
```Traceback (most recent call last):
  File "/Users/$USERNAME/noisemaker/bin/animaker", line 10, in <module>
    sys.exit(main())
  File "/Users/$USERNAME/noisemaker/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/$USERNAME/noisemaker/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/$USERNAME/noisemaker/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/$USERNAME/noisemaker/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/$USERNAME/noisemaker/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/$USERNAME/noisemaker/lib/python3.7/site-packages/noisemaker/scripts/animaker.py", line 97, in main
    
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 342, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 323, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'convert': 'convert'
```

I've looked everywhere I can think of, but the error keeps coming back to haunt my tired little head, so I would appreciate it if this gets some attention. Thanks! :)

*Additional Info:*
OS: MacOS Mojave 1.14.6
Python version 3.7
Ran via Terminal in a custom directory with the command: `animaker --save-frames ./frames --name noisething.gif random`

**Comment by BumpierZulu9930** [comment]
Huh, seems to work after I installed ImageMagick. Maybe _that_ is the culprit?

**Comment by aayars** [comment]
Sorry for missing this. Yeah, ImageMagick needs to be installed in the environment for animaker.

**Comment by aayars** [comment]
Added a note about animaker requiring ImageMagick to the docs. Sorry for the trouble!
